-- One ready-to-use account per role, for manual testing of the API.
-- Hand-written (unlike seed.sql, which is generated by Ticket Tout/dev/generate-seed.ts).
--
-- Apply AFTER seed.sql — it reuses administration id 1, companyValidationReason
-- id 1, companyCategory id 1 and the seeded partner company "Le Bistrot des
-- Halles". Re-running it is safe: every statement is ON CONFLICT DO NOTHING.
--
-- Credentials are listed in login.txt, in this folder.
--
--   docker compose --env-file .env.development up -d db
--   docker exec -i ticket_tout_db psql -U postgres -d tickettout < mocks/seed.sql
--   docker exec -i ticket_tout_db psql -U postgres -d tickettout < mocks/seed-roles.sql

BEGIN;

-- document
-- Users.documentId and Company.kbisId are both NOT NULL and UNIQUE, so each new
-- account needs its own document row.
INSERT INTO public.document (id, "storageKey", "mimeType", size, "createdAt") VALUES
  ('d0000000-0000-4000-8000-000000000001', 'seed/roles/admin.pdf',    'application/pdf', 120000, '2026-06-03T00:00:00Z'),
  ('d0000000-0000-4000-8000-000000000002', 'seed/roles/company.pdf',  'application/pdf', 130000, '2026-06-03T00:00:00Z'),
  ('d0000000-0000-4000-8000-000000000003', 'seed/roles/partner.pdf',  'application/pdf', 140000, '2026-06-03T00:00:00Z'),
  ('d0000000-0000-4000-8000-000000000004', 'seed/roles/employee.pdf', 'application/pdf', 150000, '2026-06-03T00:00:00Z'),
  ('d0000000-0000-4000-8000-000000000005', 'seed/roles/kbis.pdf',     'application/pdf', 160000, '2026-06-03T00:00:00Z')
ON CONFLICT (id) DO NOTHING;

-- company
-- Every company in seed.sql is a partner (isPartner = TRUE), so the COMPANY and
-- EMPLOYEE accounts below need an employer company to belong to.
INSERT INTO public.company (id, name, email, siret, "kbisId", address, "postalCode", "agentId", "reasonId", verified, "isFeatured", "categoryId", location, "isPartner", active, "createdAt", "updatedAt") VALUES
  ('c0000000-0000-4000-8000-000000000001', 'Employeur Test SA', 'contact@employeur-test.fr', '90000000000017', 'd0000000-0000-4000-8000-000000000005', '1 place de la Mairie', '75011', 1, 1, TRUE, FALSE, 1, ST_SetSRID(ST_MakePoint(2.3765, 48.8580), 4326), FALSE, TRUE, '2026-06-03T00:00:00Z', '2026-06-03T00:00:00Z')
ON CONFLICT (id) DO NOTHING;

-- users
-- One per role. Passwords are SHA-256 hashed, matching hashPassword() in
-- Ticket Tout/lib/services/auth_service.ts.
--
-- companyId is what the API's ownership checks read:
--   ADMIN    -> NULL, an admin is not tied to a company and bypasses those checks
--   COMPANY  -> the employer it administers
--   EMPLOYEE -> the employer it works for
--   PARTNER  -> the partner company it administers
INSERT INTO public.users (id, email, surname, name, role, balance, password, "createdAt", "updatedAt", "expiredAt", "documentId", "companyId") VALUES
  ('a0000000-0000-4000-8000-000000000001', 'admin@tickettout.test',    'Admin',    'Test', 'ADMIN',    0,    '0a2e11f7ea9034fca55047b9242ec2fc0d07c8d6d2b93b6867fd091de3b87d68', '2026-06-03T00:00:00Z', '2026-06-03T00:00:00Z', NULL, 'd0000000-0000-4000-8000-000000000001', NULL),
  ('a0000000-0000-4000-8000-000000000002', 'company@tickettout.test',  'Company',  'Test', 'COMPANY',  0,    '8503abeb1252ceca9272c25f275767fcaa07db3a21cd54e971063488d96f3002', '2026-06-03T00:00:00Z', '2026-06-03T00:00:00Z', NULL, 'd0000000-0000-4000-8000-000000000002', 'c0000000-0000-4000-8000-000000000001'),
  ('a0000000-0000-4000-8000-000000000003', 'partner@tickettout.test',  'Partner',  'Test', 'PARTNER',  0,    '97d794897dd24b8efcd91427ae1bec443c11b7e5673e653068f129169a30352f', '2026-06-03T00:00:00Z', '2026-06-03T00:00:00Z', NULL, 'd0000000-0000-4000-8000-000000000003', 'a0f9dfc0-b6d4-4001-8880-c12c01b44f24'),
  ('a0000000-0000-4000-8000-000000000004', 'employee@tickettout.test', 'Employee', 'Test', 'EMPLOYEE', 5000, '13d0629490065e5127d84f544c641e4b187f932044325a3d53c565eeb8a33ce7', '2026-06-03T00:00:00Z', '2026-06-03T00:00:00Z', NULL, 'd0000000-0000-4000-8000-000000000004', 'c0000000-0000-4000-8000-000000000001')
ON CONFLICT (id) DO NOTHING;

COMMIT;
